# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 03:24
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('broadcast', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval_time', models.CharField(default=5, max_length=20)),
                ('begin_time', models.CharField(default='07:00', max_length=20)),
                ('end_time', models.CharField(default='23:00', max_length=20)),
                ('is_valid', models.BooleanField(default=True)),
                ('update_time', models.DateTimeField(default=datetime.datetime(2017, 10, 24, 11, 24, 42, 423030))),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
