# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-27 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tkuser',
            name='inviter_id',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
