# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-27 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast', '0002_tkuser_inviter_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tkuser',
            name='avatar_url',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='tkuser',
            name='inviter_backup_info',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
