# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 03:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast', '0002_pushtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushtime',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 24, 11, 28, 20, 159526)),
        ),
    ]
