# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 03:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast', '0003_auto_20171024_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushtime',
            name='update_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
