# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-27 09:34
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0, verbose_name=b'\xe9\x87\x91\xe9\xa2\x9d')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AccountFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=16, verbose_name=b'\xe7\x94\xa8\xe6\x88\xb7ID')),
                ('type', models.CharField(max_length=16, verbose_name=b'\xe7\xbb\x93\xe7\xae\x97\xe7\xb1\xbb\xe5\x9e\x8b')),
                ('in_or_out', models.BooleanField(default=True, verbose_name=b'\xe5\x87\xba\xe5\x85\xa5\xe8\xb4\xa6')),
                ('amount', models.FloatField(default=0, verbose_name=b'\xe9\x87\x91\xe9\xa2\x9d')),
                ('order_id', models.CharField(max_length=50, verbose_name=b'\xe8\xae\xa2\xe5\x8d\x95ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AgentCommision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField(default=0, verbose_name=b'\xe8\xb4\xa6\xe6\x88\xb7\xe9\x87\x91\xe9\xa2\x9d')),
                ('sum_earning_amount', models.FloatField(default=0, verbose_name=b'\xe6\x80\xbb\xe4\xbd\xa3\xe9\x87\x91')),
                ('sum_payed_amount', models.FloatField(default=0, verbose_name=b'\xe5\xb7\xb2\xe6\x8f\x90\xe7\x8e\xb0\xe9\x87\x91\xe9\xa2\x9d')),
                ('commission_rate', models.FloatField(default=0.05)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AgentOrderStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=30, verbose_name=b'\xe8\xae\xa2\xe5\x8d\x95id')),
                ('enter_account', models.BooleanField(default=True, verbose_name=b'\xe6\x98\xaf\xe5\x90\xa6\xe5\x85\xa5\xe8\xb4\xa6')),
            ],
        ),
        migrations.CreateModel(
            name='AlipayAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alipay_id', models.CharField(max_length=40, verbose_name=b'\xe6\x94\xaf\xe4\xbb\x98\xe5\xae\x9d\xe8\xb4\xa6\xe6\x88\xb7')),
                ('alipay_name', models.CharField(max_length=10, verbose_name=b'\xe6\x94\xaf\xe4\xbb\x98\xe5\xae\x9d\xe7\x94\xa8\xe6\x88\xb7\xe5\xa7\x93\xe5\x90\x8d')),
                ('identity_num', models.CharField(max_length=18, verbose_name=b'\xe8\xba\xab\xe4\xbb\xbd\xe8\xaf\x81\xe5\x8f\xb7\xe7\xa0\x81')),
                ('phone_num', models.CharField(max_length=11, verbose_name=b'\xe6\x89\x8b\xe6\x9c\xba\xe5\x8f\xb7\xe7\xa0\x81')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Commision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField(default=0, verbose_name=b'\xe8\xb4\xa6\xe6\x88\xb7\xe9\x87\x91\xe9\xa2\x9d')),
                ('sum_earning_amount', models.FloatField(default=0, verbose_name=b'\xe6\x80\xbb\xe4\xbd\xa3\xe9\x87\x91')),
                ('sum_payed_amount', models.FloatField(default=0, verbose_name=b'\xe5\xb7\xb2\xe6\x8f\x90\xe7\x8e\xb0\xe9\x87\x91\xe9\xa2\x9d')),
                ('is_valid', models.BooleanField(default=True)),
                ('commision_rate', models.FloatField(default=0.15)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField()),
                ('click_time', models.DateTimeField(null=True)),
                ('good_info', models.CharField(max_length=255, verbose_name=b'\xe5\x95\x86\xe5\x93\x81\xe4\xbf\xa1\xe6\x81\xaf')),
                ('good_id', models.CharField(max_length=255, verbose_name=b'\xe5\x95\x86\xe5\x93\x81id')),
                ('wangwang', models.CharField(max_length=255, verbose_name=b'\xe6\x8e\x8c\xe6\x9f\x9c\xe6\x97\xba\xe6\x97\xba')),
                ('shop', models.CharField(max_length=255, verbose_name=b'\xe6\x89\x80\xe5\xb1\x9e\xe5\xba\x97\xe9\x93\xba')),
                ('good_num', models.IntegerField()),
                ('good_price', models.FloatField()),
                ('order_status', models.CharField(max_length=255, verbose_name=b'\xe8\xae\xa2\xe5\x8d\x95\xe7\x8a\xb6\xe6\x80\x81')),
                ('order_type', models.CharField(max_length=255, verbose_name=b'\xe8\xae\xa2\xe5\x8d\x95\xe7\xb1\xbb\xe5\x9e\x8b')),
                ('earning_rate', models.CharField(max_length=255, verbose_name=b'\xe6\x94\xb6\xe5\x85\xa5\xe6\xaf\x94\xe7\x8e\x87')),
                ('share_rate', models.CharField(max_length=255, verbose_name=b'\xe5\x88\x86\xe6\x88\x90\xe6\xaf\x94\xe7\x8e\x87')),
                ('pay_amount', models.FloatField()),
                ('result_predict', models.FloatField()),
                ('balance_amount', models.FloatField()),
                ('money_amount', models.FloatField()),
                ('earning_time', models.DateTimeField(blank=True, null=True)),
                ('commision_rate', models.CharField(max_length=255, verbose_name=b'\xe4\xbd\xa3\xe9\x87\x91\xe6\xaf\x94\xe7\x8e\x87')),
                ('commision_amount', models.FloatField()),
                ('show_commision_amount', models.FloatField()),
                ('show_commision_rate', models.CharField(max_length=255, verbose_name=b'\xe6\x98\xbe\xe7\xa4\xba\xe4\xbd\xa3\xe9\x87\x91\xe6\xaf\x94\xe7\x8e\x87')),
                ('subsidy_rate', models.CharField(max_length=255, verbose_name=b'\xe8\xa1\xa5\xe8\xb4\xb4\xe6\xaf\x94\xe7\x8e\x87')),
                ('subsidy_amount', models.FloatField()),
                ('subsidy_type', models.CharField(max_length=255, verbose_name=b'\xe8\xa1\xa5\xe8\xb4\xb4\xe7\xb1\xbb\xe5\x9e\x8b')),
                ('terminalType', models.CharField(max_length=255, verbose_name=b'\xe6\x88\x90\xe4\xba\xa4\xe5\xb9\xb3\xe5\x8f\xb0')),
                ('third_service', models.CharField(max_length=255, verbose_name=b'\xe7\xac\xac\xe4\xb8\x89\xe6\x96\xb9\xe6\x9c\x8d\xe5\x8a\xa1')),
                ('order_id', models.CharField(max_length=255, unique=True, verbose_name=b'\xe8\xae\xa2\xe5\x8d\x95\xe7\xbc\x96\xe5\x8f\xb7')),
                ('category_name', models.CharField(max_length=255, verbose_name=b'\xe7\xb1\xbb\xe7\x9b\xae\xe5\x90\x8d\xe7\xa7\xb0')),
                ('source_id', models.CharField(max_length=255, verbose_name=b'\xe6\x9d\xa5\xe6\xba\x90id')),
                ('source_media', models.CharField(max_length=255, verbose_name=b'\xe6\x9d\xa5\xe6\xba\x90\xe5\xaa\x92\xe4\xbd\x93')),
                ('ad_id', models.CharField(max_length=255, verbose_name=b'\xe5\xb9\xbf\xe5\x91\x8a\xe4\xbd\x8did')),
                ('ad_name', models.CharField(max_length=255, verbose_name=b'\xe5\xb9\xbf\xe5\x91\x8a\xe4\xbd\x8d\xe5\x90\x8d\xe7\xa7\xb0')),
                ('last_update_time', models.DateTimeField(default=datetime.datetime.now)),
                ('enter_account', models.BooleanField(default=False)),
            ],
        ),
    ]
