# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-27 09:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agentcommision',
            old_name='commission_rate',
            new_name='commision_rate',
        ),
    ]
