# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipad_weixin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupmembers',
            old_name='name',
            new_name='username',
        ),
        migrations.AddField(
            model_name='groupmembers',
            name='inviter_username',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='groupmembers',
            name='nickname',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='groupmembers',
            name='small_head_img_url',
            field=models.URLField(default=''),
        ),
    ]
