# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast', '0001_initial'),
        ('ipad_weixin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wxuser',
            name='tk_user',
            field=models.ManyToManyField(to='broadcast.TkUser'),
        ),
    ]
