# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipad_weixin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wxuser',
            name='uuid',
            field=models.CharField(default=None, max_length=150),
        ),
    ]
