# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-26 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipad_weixin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='msg_source',
            field=models.TextField(),
        ),
    ]
