# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 06:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipad_weixin', '0002_chatroom_chat_room_version'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wxuser',
            old_name='groups',
            new_name='chatroom',
        ),
    ]
