# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 10:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ipad_weixin', '0002_wxuser_tk_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wxuser',
            name='tk_user',
        ),
        migrations.AddField(
            model_name='wxuser',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
