# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 03:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipad_weixin', '0002_auto_20171022_1220'),
        ('ipad_weixin', '0002_auto_20171020_1646'),
    ]

    operations = [
    ]
