# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipad_weixin', '0002_wxuser_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wxuser',
            name='last_heart_beat',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
