# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipad_weixin', '0002_auto_20170919_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignInRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=200)),
                ('keyword', models.TextField()),
                ('red_packet_id', models.CharField(max_length=100)),
            ],
        ),
    ]
