# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipad_weixin', '0002_auto_20170929_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmembers',
            name='members_nums',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
