# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 02:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipad_weixin', '0003_auto_20171008_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signinrule',
            name='group_name',
        ),
        migrations.AddField(
            model_name='signinrule',
            name='chatroom',
            field=models.ManyToManyField(to='ipad_weixin.ChatRoom'),
        ),
        migrations.AddField(
            model_name='signinrule',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
