# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipad_weixin', '0003_auto_20170930_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wxuser',
            name='chatroom',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='wx_user',
            field=models.ManyToManyField(to='ipad_weixin.WxUser'),
        ),
    ]
