# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 09:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipad_weixin', '0003_groupmembers_members_nums'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupmembers',
            old_name='members_nums',
            new_name='member_nums',
        ),
    ]
