# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipad_weixin', '0004_auto_20170930_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='wx_user',
            field=models.ManyToManyField(to='ipad_weixin.WxUser'),
        ),
    ]
