# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipad_weixin', '0004_auto_20170929_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmembers',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
