# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipad_weixin', '0005_groupmembers_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmembers',
            name='member_nums',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='member_nums',
            field=models.IntegerField(default=0),
        ),
    ]
