# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipad_weixin', '0006_auto_20170929_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmembers',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
